name: neccton_no3
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.2
  - numpy=1.26.4
  - pandas=2.2.3
  - xarray=2024.5.0
  - scipy=1.13.0
  - scikit-learn=1.5.1
  - matplotlib=3.9.0
  - netcdf4=1.7.1
  - dask=2024.5.1
  - xesmf=0.8.5
  - bottleneck=1.3.8
  - pip:
      - autokeras==1.2.0
      - tensorflow==2.15.0
      - tpot==0.12.1
